[EDIT]syntax of ifs executable not found again beacause i forgot . after grep

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -47,9 +47,9 @@ jobs:
             timeout-minutes: 2
             run: make clean
           - name: Executable
-            run: IFS=',' read -ra ex <<< ${{ env.EXECUTABLES }} ; for value in ${ex[@]} ; do find . -executable -name "${value}" | grep -q ||echo "::error file={},title="Executable not found"::${value}"; done
+            run: IFS=',' read -ra ex <<< ${{ env.EXECUTABLES }} ; for value in ${ex[@]} ; do find . -executable -name "${value}" | grep -q . ||echo "::error file={},title="Executable not found"::${value}"; done
           - name: Executable not here
-            run: IFS=',' read -ra ex <<< ${{ env.EXECUTABLES }} ; for value	in ${ex[@]} ; do find . -executable -name "${value}" | grep -q || exit 1 ; done
+            run: IFS=',' read -ra ex <<< ${{ env.EXECUTABLES }} ; for value	in ${ex[@]} ; do find . -executable -name "${value}" | grep -q . || exit 1 ; done
     run_tests:
         name: check test
         runs-on: ubuntu-latest
